In [ ]:
import numpy as np
import pandas as pd

In [ ]:
url = "https://raw.githubusercontent.com/aswintechguy/Machine-Learning-Projects/master/IMDB%20Movies%20Dataset%20-%20Recommendation%20Engine/IMDB_Top250Engmovies2_OMDB_Detailed.csv"
data = pd.read_csv(url)
data

In [ ]:
data.describe()

In [ ]:
data.info()

In [ ]:
data.isnull().sum()

**For Object type data Pre-Processing**

In [66]:
data['Awards'] = data['Awards'].fillna(data['Awards'].mode()[0])
data['Released'] = data['Released'].fillna(data['Released'].mode()[0])
data['Writer'] = data['Writer'].fillna(data['Writer'].mode()[0])
data['DVD'] = data['DVD'].fillna(data['DVD'].mode()[0])
data['BoxOffice'] = data['BoxOffice'].fillna(data['BoxOffice'].mode()[0])
data['Website'] = data['Website'].fillna(data['Website'].mode()[0])

**For Numeric type data Pre-Processing**

In [ ]:
# # Dropped colums according a condition where null values are greter than 0
# df1 = data.drop(data.columns[data.apply(lambda col:col.isna().sum()>0)], axis=1)
# df1.isnull().sum()
# Dropped colums according to their names 
droped_columns = ['tomatoImage', 'tomatoRating', 'tomatoReviews', 'tomatoFresh', 'tomatoRotten', 'tomatoConsensus', 'tomatoUserRating', 'tomatoUserReviews', 'tomatoMeter', 'tomatoUserMeter']
dataset1 = data.drop(columns=droped_columns)
dataset1.isnull().sum()